/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/PeopleTable copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PeopleTable: typeof import('./src/components/PeopleTable.vue')['default']
    PlanetsTable: typeof import('./src/components/PlanetsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
