version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - BASE_URL=${BASE_URL}

  frontend:
    build:
      context: ./frontend
    environment:
      - EXPOSED_PORT=${EXPOSED_PORT}
    ports:
      - "${EXPOSED_PORT}:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
